const isDarkMode = window.matchMedia('(prefers-color-scheme: Dark)').matches;

const BASE_COLORS = {
  // prettier-ignore
  bnw:       ['#000000', '#FFFFFF'],
  // prettier-ignore
  primary:   ['#0E3566', '#174C99', '#2261CC', '#2E74FF', '#5594FF', '#7DB2FF', '#A7CEFF'],
  // prettier-ignore
  secondary: ['#3D3D3D', '#5C5C5C', '#7A7A7A', '#999999', '#ADADAD', '#C2C2C2', '#D6D6D6'],
  // prettier-ignore
  danger:    ['#601515', '#8E2521', '#BB372E', '#E74C3C', '#EE6A61', '#F48B87', '#F9AEAE'],
  // prettier-ignore
  warning:   ['#663703', '#965706', '#C5780B', '#F39C12', '#F8AB3E', '#FCBD6C', '#FFD09C'],
  // prettier-ignore
  success:   ['#0D4821', '#156B34', '#1D8D49', '#27AE60', '#50C07C', '#7BD19A', '#A6E1BA'],
  // prettier-ignore
  info:      ['#361947', '#52276A', '#70358C', '#8E44AD', '#A368BF', '#B88DD0', '#CFB2E0'],
};

const LIGHT_COLORS = {
  Black: BASE_COLORS.bnw[0],
  White: BASE_COLORS.bnw[1],
  Primary1: BASE_COLORS.primary[0],
  Primary2: BASE_COLORS.primary[1],
  Primary3: BASE_COLORS.primary[2],
  Primary4: BASE_COLORS.primary[3],
  Primary5: BASE_COLORS.primary[4],
  Primary6: BASE_COLORS.primary[5],
  Primary7: BASE_COLORS.primary[6],
  Secondary1: BASE_COLORS.secondary[0],
  Secondary2: BASE_COLORS.secondary[1],
  Secondary3: BASE_COLORS.secondary[2],
  Secondary4: BASE_COLORS.secondary[3],
  Secondary5: BASE_COLORS.secondary[4],
  Secondary6: BASE_COLORS.secondary[5],
  Secondary7: BASE_COLORS.secondary[6],
  Danger1: BASE_COLORS.danger[0],
  Danger2: BASE_COLORS.danger[1],
  Danger3: BASE_COLORS.danger[2],
  Danger4: BASE_COLORS.danger[3],
  Danger5: BASE_COLORS.danger[4],
  Danger6: BASE_COLORS.danger[5],
  Danger7: BASE_COLORS.danger[6],
  Warning1: BASE_COLORS.warning[0],
  Warning2: BASE_COLORS.warning[1],
  Warning3: BASE_COLORS.warning[2],
  Warning4: BASE_COLORS.warning[3],
  Warning5: BASE_COLORS.warning[4],
  Warning6: BASE_COLORS.warning[5],
  Warning7: BASE_COLORS.warning[6],
  Success1: BASE_COLORS.success[0],
  Success2: BASE_COLORS.success[1],
  Success3: BASE_COLORS.success[2],
  Success4: BASE_COLORS.success[3],
  Success5: BASE_COLORS.success[4],
  Success6: BASE_COLORS.success[5],
  Success7: BASE_COLORS.success[6],
  Info1: BASE_COLORS.info[0],
  Info2: BASE_COLORS.info[1],
  Info3: BASE_COLORS.info[2],
  Info4: BASE_COLORS.info[3],
  Info5: BASE_COLORS.info[4],
  Info6: BASE_COLORS.info[5],
  Info7: BASE_COLORS.info[6],
};

const DARK_COLORS = {
  Black: BASE_COLORS.bnw[1],
  White: BASE_COLORS.bnw[0],
  Primary1: BASE_COLORS.primary[6],
  Primary2: BASE_COLORS.primary[5],
  Primary3: BASE_COLORS.primary[4],
  Primary4: BASE_COLORS.primary[3],
  Primary5: BASE_COLORS.primary[2],
  Primary6: BASE_COLORS.primary[1],
  Primary7: BASE_COLORS.primary[0],
  Secondary1: BASE_COLORS.secondary[6],
  Secondary2: BASE_COLORS.secondary[5],
  Secondary3: BASE_COLORS.secondary[4],
  Secondary4: BASE_COLORS.secondary[3],
  Secondary5: BASE_COLORS.secondary[2],
  Secondary6: BASE_COLORS.secondary[1],
  Secondary7: BASE_COLORS.secondary[0],
  Danger1: BASE_COLORS.danger[6],
  Danger2: BASE_COLORS.danger[5],
  Danger3: BASE_COLORS.danger[4],
  Danger4: BASE_COLORS.danger[3],
  Danger5: BASE_COLORS.danger[2],
  Danger6: BASE_COLORS.danger[1],
  Danger7: BASE_COLORS.danger[0],
  Warning1: BASE_COLORS.warning[6],
  Warning2: BASE_COLORS.warning[5],
  Warning3: BASE_COLORS.warning[4],
  Warning4: BASE_COLORS.warning[3],
  Warning5: BASE_COLORS.warning[2],
  Warning6: BASE_COLORS.warning[1],
  Warning7: BASE_COLORS.warning[0],
  Success1: BASE_COLORS.success[6],
  Success2: BASE_COLORS.success[5],
  Success3: BASE_COLORS.success[4],
  Success4: BASE_COLORS.success[3],
  Success5: BASE_COLORS.success[2],
  Success6: BASE_COLORS.success[1],
  Success7: BASE_COLORS.success[0],
  Info1: BASE_COLORS.info[6],
  Info2: BASE_COLORS.info[5],
  Info3: BASE_COLORS.info[4],
  Info4: BASE_COLORS.info[3],
  Info5: BASE_COLORS.info[2],
  Info6: BASE_COLORS.info[1],
  Info7: BASE_COLORS.info[0],
};

// TODO: Support Dark Mode
export const colors = isDarkMode ? LIGHT_COLORS : LIGHT_COLORS;
